### ISSUE TITLE
Add support for multi-folder projects

### ISSUE THREAD

**Issue by zero-enthusiasm** [ZhangJian1713/vscode-image-viewer#12]
This extension is great and just what I've been looking for to replace a more cumbersome tool we use instead but unfortunately it does not work with our project structure.

We have 2 folders: Source and Deploy. All our images are in Deploy and do not get found by the extension. The issue is caused by getProjectPath which gets all the vscode workspace folders but always returns only the first entry (Source in our case).

I have fixed this locally by modifying the extension.js file but it's not easy to roll it out to everyone else with that solution . I had a look through the repo and it looks like getProjectPath is imported from another package I can't find any info on?

Thanks!

**Comment by ZhangJian1713** [comment]
Yeah. `getProjectPath` is imported from my other project [https://github.com/ZhangJian1713/easy-vscode](https://github.com/ZhangJian1713/easy-vscode). It's designed to help everyone build VSCode extension easily.

Image Viewer is designed to view images according to the directory, and I tested that it can detect multiple folders under the root directory. After removing sensitive information, I'd like to see your directory structure and modification to extension.js to fix the problem.

**Comment by Baboonanza** [comment]
I've created a pull request with my fix that seems to work pretty well: https://github.com/ZhangJian1713/vscode-image-viewer/pull/13

I've tested both single and multi-folder workspaces and both now work. I'm sure you'll want to make changes but this should be most of the way there.

**Comment by Baboonanza** [comment]
[Projects.zip](https://github.com/ZhangJian1713/vscode-image-viewer/files/13743009/Projects.zip)
And here are the multi and single folder wrokspace sI was testing with

**Comment by zero-enthusiasm** [comment]
Due to it taking too long to update the extension I just re-implemented it: https://github.com/zero-enthusiasm/vscode-project-image-browser so the pull request is no longer required.
