### ISSUE TITLE
窗口中图像的Previewer没有实时的显示变化，刷新也不行

### ISSUE THREAD

**Issue by terrencew** [ZhangJian1713/vscode-image-viewer#15]
感谢作者的辛勤付出，方便了我的开发工作，真心感谢。

反馈的Issue是：
Images Viewer能够显示图片的Preview信息，比如图片长宽和大小等，但是当图片发生变化时（比如大小变了），该窗口中Viewer点击刷新后也不能显示这一变化。

另外经测试，重新打开Viewer窗口可以显示最新的图片信息。

**Comment by ZhangJian1713** [comment]
谢谢反馈哦，已经修复了。
