### ISSUE TITLE
Uppercase files extensions

### ISSUE THREAD

**Issue by ews-ffarella** [ZhangJian1713/vscode-image-viewer#21]
I think it would be great to:

- Either add an option to modify `showImageTypes` as an extension option
- and / or at least at the uppercase version of some extensions like 'JPG',  'JPEG',  'PNG', etc ...

Anyways, great extension 😃

**Comment by ZhangJian1713** [comment]
I didn't quite get the meaning of request-1. Could you please elaborate further? 
As for request-2, I'll fix and update it ASAP.

**Comment by ews-ffarella** [comment]
The first comment was that maybe one could configure the file extensions that should be discovered. As an option. 
And thanks for considering the second possibility ;)

**Comment by ZhangJian1713** [comment]
I have fixed support for uppercase image file extensions.

**Comment by ZhangJian1713** [comment]
> The first comment was that maybe one could configure the file extensions that should be discovered. As an option. And thanks for considering the second possibility ;)

I've tried to include all supported image types so users don't have to concern about it. Currently I have no plans to introduce a way for users to manually input this. 

The supported image types now include:
`export const SUPPORT_IMG_TYPES = ['.svg', '.png', '.jpeg', '.jpg', '.ico', '.gif', '.webp', '.bmp', '.tif', '.tiff', '.apng', '.avif']`
