### ISSUE TITLE
[Feature Request] 希望支持在特定的目录下查看图片

### ISSUE THREAD

**Issue by liutaigang** [ZhangJian1713/vscode-image-viewer#4]
希望支持在特定的目录下查看图片

特别是我确定我需要查找的图片在某个文件中时，或者在 monorepe 的代码仓中，我并不希望查看所有项目的图片

![image](https://github.com/ZhangJian1713/vscode-image-viewer/assets/110760655/955456c2-a267-4975-832b-6f9013533438)

**Comment by zj131711** [comment]
右键点击项目内某个文件夹并执行 “View Images”，会根据这个文件夹进行筛选，可以点击 X 取消筛选。因为没有实际渲染，性能应当影响比较小。
<img width="1458" alt="image" src="https://github.com/ZhangJian1713/vscode-image-viewer/assets/96158543/66380537-17b4-43e1-bcf9-f8f66b9e25d7">

如果右键点击的是单个图片文件，也会根据文件的上层文件夹进行筛选，并将图片调整到第一个显示，并且自动打开预览。

以上是否已经符合你的需求？

**Comment by ZhangJian1713** [comment]
右键点击项目内某个文件夹并执行 “View Images”，会根据这个文件夹进行筛选，可以点击 X 取消筛选。因为没有实际渲染，性能应当影响比较小。
<img width="1458" alt="image" src="https://github.com/ZhangJian1713/vscode-image-viewer/assets/96158543/66380537-17b4-43e1-bcf9-f8f66b9e25d7">

如果右键点击的是单个图片文件，也会根据文件的上层文件夹进行筛选，并将图片调整到第一个显示，并且自动打开预览。

以上是否已经符合你的需求？

**Comment by aihao2000** [comment]
@ZhangJian1713 当工作区有多个文件夹时，希望可以直接看其他文件夹的图片

**Comment by ZhangJian1713** [comment]
> @ZhangJian1713 当工作区有多个文件夹时，希望可以直接看其他文件夹的图片

你是否指的是 #12 的同一问题？将会在那个 issue 中跟进修复
