### ISSUE TITLE
Great extension! But found that the tif image cannot be displayed 

### ISSUE THREAD

**Issue by zhouxinghong** [ZhangJian1713/vscode-image-viewer#7]
Great extension!
But found that the tif image cannot be displayed
![image](https://github.com/ZhangJian1713/vscode-image-viewer/assets/54253524/ea2e3c90-1085-4dc5-821f-a902d10966de)
Windows 10
VSCode1.8.3
Extensions: 1.5.3

**Comment by ZhangJian1713** [comment]
The issue does exist. The browser does not support the tiff format. I will process this after the "exclude path" issue.
