### ISSUE TITLE
Support Markdown online image preview and local image preview

### ISSUE THREAD

**Issue by zhouxinghong** [ZhangJian1713/vscode-image-viewer#9]
Support Markdown online image preview and local image preview

Request support for Markdown online image preview and local image preview
Windows 10
VSCode 1.83
View Images 1.5.3

**Comment by ZhangJian1713** [comment]
I don't quite understand this requirement. If what you're looking for is a Markdown previewer, I believe that VSCode already has this feature, or there are many other extensions that have already implemented this feature.
